language: ruby

branches:
  only:
    - master

sudo: required
cache: bundler
services:
  - docker

install:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

before_script:
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec rake && chef exec kitchen test
